name: ecotrak_test
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Fixed: Compatible with your Dart 3.7.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Updated Firebase dependencies to their latest stable versions
  firebase_core: ^2.25.3
  firebase_auth: ^4.17.2
  cloud_firestore: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/yoshi.png
    - assets/images/ecotrakLogo.png